<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="KoreForge.Json" VersionOverride="1.0.1-alpha" />
    <PackageReference Include="KoreForge.Jex" />
  </ItemGroup>

</Project>
